apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-k8s-app
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
