apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azhar-secrets  #Type Any Name that you want to give for secets creation inside cluster
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "azhar-secret"
          objectType: "secretsmanager"