apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test
data:
  APP_ENV: "dev"
  APP_DEBUG: "true"
---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s-app
  template:
    metadata:
      labels:
        app: hello-k8s-app
    spec:
      containers:
      - name: hello-k8s-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-app-service
  namespace: test
spec:
  selector:
    app: hello-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.sherdilitacademy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-k8s-app-service
            port:
              number: 80
