# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-k8s-app
  template:
    metadata:
      labels:
        app: hello-k8s-app
    spec:
      containers:
      - name: hello-k8s-app
        image: nginx:alpine
        ports:
        - containerPort: 80
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-app-service
spec:
  selector:
    app: hello-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: test-ingress
#   annotations:
# #    kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     alb.ingress.kubernetes.io/group.name: sherdil
# spec:
#   rules:
#   - host: test.sherdilitacademy.net
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: hello-k8s-app-service
#             port:
#               number: 80
