apiVersion: v1
kind: Service
metadata:
  name: grpcmicroservice-service
spec:
  selector:
    app: stggrpcmicroservice
  type: 
  ports:
    - protocol: TCP
      port: 8080
      port: 9090
      targetPort: 8080